name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_SECRET: "FAKE"
  NEXTAUTH_URL: "https://fake.com"
  DISCORD_CLIENT_ID: "FAKE"
  DISCORD_CLIENT_SECRET: "FAKE"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Types
        run: npm run postinstall

      - name: Typecheck
        run: npm run typecheck -- -p typecheck-tsconfig.json

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
